[tool.poetry]
name = "tap-bitly"
version = "0.0.1"
description = "`tap-bitly` is a Singer tap for Bitly, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramirez-Mondragon <edgarrm358@gmail.com>"]
keywords = [
  "ELT",
  "singer.io",
  "Bitly",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-bitly"
repository = "https://github.com/edgarrmondragon/tap-bitly"
documentation = "https://github.com/edgarrmondragon/tap-bitly#readme"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "0.28.0"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_bitly"

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-bitly = "tap_bitly.tap:TapBitly.cli"

[tool.ruff]
ignore = [
  "ANN101", # missing-type-self
  "DJ", # flake8-django
]
line-length = 88
select = ["ALL"]
src = ["tap_bitly", "tests"]
target-version = "py37"

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101", # assert
  "SLF001", # private-member-access
]

[tool.ruff.isort]
known-first-party = ["tap_bitly"]

[tool.ruff.pydocstyle]
convention = "google"
