name: Test tap-bitly

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.4.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install poetry
        poetry --version

    - name: Install tox
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install tox
        tox --version

    - name: Run tests with Tox
      env:
        TAP_BITLY_TOKEN: ${{ secrets.TAP_BITLY_TOKEN }}
      run: |
        tox -e pytest
